# Data Engineering Assessment
Run the setup cell below to install the necessary PostgreSQL drivers, connect to the database, and initialize PySpark.

In [1]:
%load_ext sql
%sql postgresql://admin:password@postgres:5432/assessment_db

import pandas as pd
from pyspark.sql import SparkSession
import psycopg2

# Initialize Spark Session
spark = SparkSession.builder.appName('Assessment').getOrCreate()

# Load data into Pandas
conn = psycopg2.connect(host='postgres', dbname='assessment_db', user='admin', password='password')
df_customers = pd.read_sql('SELECT * FROM customers', conn)
df_products = pd.read_sql('SELECT * FROM products', conn)
df_orders = pd.read_sql('SELECT * FROM orders', conn)

# Load data into PySpark DataFrames
spark_customers = spark.createDataFrame(df_customers)
spark_products = spark.createDataFrame(df_products)
spark_orders = spark.createDataFrame(df_orders)
print("Environment initialized successfully!")

/tmp/ipykernel_468/70256034.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_customers = pd.read_sql('SELECT * FROM customers', conn)
/tmp/ipykernel_468/70256034.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_products = pd.read_sql('SELECT * FROM products', conn)
/tmp/ipykernel_468/70256034.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_orders = pd.read_sql('SELECT * FROM orders', conn)

Environment initialized successfully!

## Part 1: SQL
Write a query to find the `name` of the customer, the `product_name`, and the total cost of their order (`quantity * price`). Only include **'Completed'** orders where the customer is from the **'USA'**.

In [2]:
# %%sql
conn = 'postgresql://admin:password@postgres:5432/assessment_db'

pd.read_sql("""
SELECT 
    -- c.name,
    p.product_name,
    SUM(o.quantity * p.price) AS price_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
LEFT JOIN products p
    ON o.product_id = p.product_id
WHERE c.country = 'USA' AND o.status = 'Completed'
GROUP BY p.product_name
""", conn)

  product_name  price_orders
0        Chair         850.0
1       Laptop        1200.0
2        Mouse          50.0

In [3]:
pd.read_sql("""
SELECT 
    *
FROM orders
""", conn)

   order_id  customer_id  product_id  order_date  quantity     status
0         1            1           1  2023-10-01         1  Completed
1         2            1           2  2023-10-02         2  Completed
2         3            2           3  2023-10-03         1  Completed
3         4            3           4  2023-10-04        10  Completed
4         5            4           2  2023-10-05         5    Pending
5         6            1           4  2023-10-06         1  Cancelled

In [4]:
pd.read_sql("""
SELECT 
    *
FROM products
""", conn)

   product_id product_name     category   price
0           1       Laptop  Electronics  1200.0
1           2        Mouse  Electronics    25.0
2           3         Desk    Furniture   150.0
3           4        Chair    Furniture    85.0

In [5]:
pd.read_sql("""
SELECT 
    category,
    SUM(o.quantity * p.price) AS total_rev
FROM products p
LEFT JOIN orders o
    ON p.product_id = o.product_id
GROUP BY category
HAVING SUM(o.quantity * p.price) > 1000 
ORDER BY total_rev DESC
""", conn)

      category  total_rev
0  Electronics     1375.0
1    Furniture     1085.0

In [6]:
# Write a SQL query that returns the transaction_id, quantity, and a new column called order_size_label using a CASE statement:
# If quantity is 5 or more, label it 'Bulk Order'
# If quantity is between 2 and 4 (inclusive), label it 'Standard Order'
# If quantity is 1, label it 'Single Item'

In [7]:
pd.read_sql("""
SELECT
    order_id,
    CASE
        WHEN quantity >= 5 THEN 'Bulk Order'
        WHEN quantity >= 2 AND quantity <= 4 THEN 'Standard Order'
        WHEN quantity = 1 THEN 'Single Item'
        ELSE 'Other' 
    END AS order_size_label
FROM orders
""", conn)

   order_id order_size_label
0         1      Single Item
1         2   Standard Order
2         3      Single Item
3         4       Bulk Order
4         5       Bulk Order
5         6      Single Item

In [8]:
# Write a SQL query to find the total number of transactions (COUNT) and the total number 
# of individual items sold (SUM of quantity) grouped by user_type. 
# Only include transactions with a status of 'Completed'.

In [9]:
pd.read_sql("""
SELECT
    c.name,
    COUNT(order_id) AS order,
    SUM(quantity) AS totol_item
FROM orders o
LEFT JOIN products p
    ON o.product_id = p.product_id
LEFT JOIN customers c
    ON o.customer_id = c.customer_id
WHERE o.status = 'Completed'
GROUP BY c.name
""", conn)

            name  order  totol_item
0    Alice Smith      2           3
1      Bob Jones      1           1
2  Charlie Brown      1          10

In [10]:
# Write a SQL query to find the user_id of all users who have made more than 3 'Completed' transactions. 
# Return the user_id and the count of their completed transactions.

In [11]:
pd.read_sql("""
SELECT
    c.customer_id,
    COUNT(o.order_id) AS order_count
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
    AND o.status = 'Completed'
GROUP BY c.customer_id
HAVING SUM(o.quantity) > 3
""", conn)

   customer_id  order_count
0            3            1

In [12]:
pd.read_sql("""
SELECT 
    product_id,
    product_name,
    DENSE_RANK() OVER(
        -- PARTITION BY product_id
        ORDER BY price DESC
    )
FROM products
""", conn)

   product_id product_name  dense_rank
0           1       Laptop           1
1           3         Desk           2
2           4        Chair           3
3           2        Mouse           4

## Part 2: Pandas
Using Pandas, write the code to calculate the total number of items sold (sum of `quantity`) for each product `category`.

In [13]:
# Write your Pandas code here
df_c = pd.read_sql("""
SELECT 
    *
FROM customers
""", conn)
df_o = pd.read_sql("""
SELECT 
    *
FROM orders
""", conn)
df_p = pd.read_sql("""
SELECT 
    *
FROM products
""", conn)

In [14]:
df_merge = df_o.merge(df_p, on='product_id', how='left')
df_merge

,order_id,customer_id,product_id,order_date,quantity,status,product_name,category,price
0,1,1,1,2023-10-01,1,Completed,Laptop,Electronics,1200.0
1,2,1,2,2023-10-02,2,Completed,Mouse,Electronics,25.0
2,3,2,3,2023-10-03,1,Completed,Desk,Furniture,150.0
3,4,3,4,2023-10-04,10,Completed,Chair,Furniture,85.0
4,5,4,2,2023-10-05,5,Pending,Mouse,Electronics,25.0
5,6,1,4,2023-10-06,1,Cancelled,Chair,Furniture,85.0

In [15]:
df_merge[df_merge['status'] == 'Completed'].groupby('category')['quantity'].agg('sum')

category
Electronics     3
Furniture      11
Name: quantity, dtype: int64

In [16]:
# You are given two Pandas DataFrames: df_transactions and df_items.
# Write the Pandas code to merge these DataFrames on item_id, filter for rows where status is 'Completed', 
# and calculate the total revenue (quantity * price) generated by each individual user_id.

In [17]:
df_merge2 = df_o.merge(df_p, on='product_id', how='left').merge(df_c, on='customer_id', how='left')
df_merge2

,order_id,customer_id,product_id,order_date,quantity,status,product_name,category,price,name,country
0,1,1,1,2023-10-01,1,Completed,Laptop,Electronics,1200.0,Alice Smith,USA
1,2,1,2,2023-10-02,2,Completed,Mouse,Electronics,25.0,Alice Smith,USA
2,3,2,3,2023-10-03,1,Completed,Desk,Furniture,150.0,Bob Jones,UK
3,4,3,4,2023-10-04,10,Completed,Chair,Furniture,85.0,Charlie Brown,USA
4,5,4,2,2023-10-05,5,Pending,Mouse,Electronics,25.0,David Lee,Canada
5,6,1,4,2023-10-06,1,Cancelled,Chair,Furniture,85.0,Alice Smith,USA

In [18]:
df_merge2[df_merge2['status'] == 'Completed'].eval('total_revenue = quantity * price').groupby('customer_id')['total_revenue'].sum()

customer_id
1    1250.0
2     150.0
3     850.0
Name: total_revenue, dtype: float64

## Part 3: PySpark
Using PySpark, write the code to create a new DataFrame showing the `customer_id` and their total lifetime spend (sum of `quantity * price` across all their completed orders).

In [19]:
# Write your PySpark code here
from pyspark.sql.functions import col, sum, when
from pyspark.sql import functions as F

In [20]:
df = (
    spark_customers
    .join(spark_orders, on="customer_id", how="left")
    .join(spark_products, on="product_id", how="left")
)
df.show()

+----------+-----------+-------------+-------+--------+----------+--------+---------+------------+-----------+------+
|product_id|customer_id|         name|country|order_id|order_date|quantity|   status|product_name|   category| price|
+----------+-----------+-------------+-------+--------+----------+--------+---------+------------+-----------+------+
|         4|          1|  Alice Smith|    USA|       6|2023-10-06|       1|Cancelled|       Chair|  Furniture|  85.0|
|         2|          1|  Alice Smith|    USA|       2|2023-10-02|       2|Completed|       Mouse|Electronics|  25.0|
|         1|          1|  Alice Smith|    USA|       1|2023-10-01|       1|Completed|      Laptop|Electronics|1200.0|
|         3|          2|    Bob Jones|     UK|       3|2023-10-03|       1|Completed|        Desk|  Furniture| 150.0|
|         4|          3|Charlie Brown|    USA|       4|2023-10-04|      10|Completed|       Chair|  Furniture|  85.0|
|         2|          4|    David Lee| Canada|       5|2023-10-05|       5|  Pending|       Mouse|Electronics|  25.0|
+----------+-----------+-------------+-------+--------+----------+--------+---------+------------+-----------+------+

In [21]:
result = df.filter(F.col("status") == "Completed").groupBy("customer_id").agg(sum(col("quantity") * col("price")).alias("lifetime_spend"))
result.show()

+-----------+--------------+
|customer_id|lifetime_spend|
+-----------+--------------+
|          1|        1250.0|
|          3|         850.0|
|          2|         150.0|
+-----------+--------------+

In [22]:
# You are given a PySpark DataFrame named spark_transactions.
# Write the PySpark DataFrame API code to add a new column named is_large_order.
# If quantity is greater than or equal to 10, the column should contain the string 'Yes'.
# Otherwise, it should contain the string 'No'.
# Finally, select only the transaction_id, quantity, and is_large_order columns to display.

In [23]:
df = spark_customers.join(spark_orders, spark_customers.customer_id == spark_orders.customer_id, 'left')\
    .join(spark_products, spark_orders.product_id == spark_products.product_id, 'left')
df = (
    spark_customers
    .join(spark_orders, on="customer_id", how="left")
    .join(spark_products, on="product_id", how="left")
)
df.show()

+----------+-----------+-------------+-------+--------+----------+--------+---------+------------+-----------+------+
|product_id|customer_id|         name|country|order_id|order_date|quantity|   status|product_name|   category| price|
+----------+-----------+-------------+-------+--------+----------+--------+---------+------------+-----------+------+
|         4|          1|  Alice Smith|    USA|       6|2023-10-06|       1|Cancelled|       Chair|  Furniture|  85.0|
|         2|          1|  Alice Smith|    USA|       2|2023-10-02|       2|Completed|       Mouse|Electronics|  25.0|
|         1|          1|  Alice Smith|    USA|       1|2023-10-01|       1|Completed|      Laptop|Electronics|1200.0|
|         3|          2|    Bob Jones|     UK|       3|2023-10-03|       1|Completed|        Desk|  Furniture| 150.0|
|         4|          3|Charlie Brown|    USA|       4|2023-10-04|      10|Completed|       Chair|  Furniture|  85.0|
|         2|          4|    David Lee| Canada|       5|2023-10-05|       5|  Pending|       Mouse|Electronics|  25.0|
+----------+-----------+-------------+-------+--------+----------+--------+---------+------------+-----------+------+

In [24]:
result = df.withColumn('is_large_order', when(col('quantity') >= 10, 'Yes').otherwise('No'))
result.select('order_id', 'quantity', 'is_large_order').show()

+--------+--------+--------------+
|order_id|quantity|is_large_order|
+--------+--------+--------------+
|       1|       1|            No|
|       3|       1|            No|
|       2|       2|            No|
|       5|       5|            No|
|       6|       1|            No|
|       4|      10|           Yes|
+--------+--------+--------------+